<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('account')->insert([
            [
                'id_account' => 'AC001',
                'username' => 'jason',
                'email' => 'jasoncliendo@gmail.com',
                'nama' => 'Jason',
                'tanggal_lahir' => '2003-08-01',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '0881026757313',
                'roles' => 'Owner',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC002',
                'username' => 'lieming',
                'email' => 'solusindosinergilelang@gmail.com',
                'nama' => 'lieming',
                'tanggal_lahir' => '1992-07-21',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082233445566',
                'roles' => 'Pengosongan',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC003',
                'username' => 'agnesia',
                'email' => 'agnesia@gmail.com',
                'nama' => 'agnes',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '083344556677',
                'roles' => 'Register',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC004',
                'username' => 'felicia',
                'email' => 'ftiffany04a@gmail.com',
                'nama' => 'felicia',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082266100102',
                'roles' => 'Agent',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC005',
                'username' => 'nyonyo',
                'email' => 'bryan@gmail.com',
                'nama' => 'bryan',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082266100102',
                'roles' => 'User',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);

        // Tabel Agent
        DB::table('agent')->insert([
            [
                'id_agent' => 'AG001',
                'id_account' => 'AC004',
                'nama' => 'felicia',
                'nomor_telepon' => '082266100102',
                'email' => 'ftiffany04a@gmail.com',
                'instagram' => 'felicia_tiffany',
                'facebook' => 'fb.com/jevon',
                'jadwal' => '2025-06-01',
                'picture' => '/storage/agents/felicia.jpg',
                'kota' => 'Surabaya',
                'status' => 'Aktif',
                'rating' => 4,
                'jumlah_penjualan' => 2,
                'lokasi_kerja' => 'Surabaya Barat',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'gambar_ktp' => '/storage/ktp/jevon_ktp.jpg',
                'gambar_npwp' => '/storage/npwp/jevon_npwp.jpg'
            ],

        ]);

        DB::table('property')->insert([
            [
                'id_listing' => 1,
                'judul' => 'Rumah Mewah di Jakarta',
                'deskripsi' => 'Rumah mewah dengan fasilitas lengkap di pusat kota.',
                'tipe' => 'rumah',
                'kamar_tidur' => 4,
                'kamar_mandi' => 3,
                'harga' => 2500000000,
                'lokasi' => 'Jl. Merdeka No. 10, Jakarta',
                'lantai' => 2,
                'id_agent' => 'AG001',
                'luas_tanah' => 300,
                'luas_bangunan' => 250,
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Pusat',
                'kelurahan' => 'Gambir',
                'sertifikat' => 'SHM',
                'orientation' => 'selatan',
                'status' => 'Tersedia',
                'gambar' => '/storage/property-images/1748617589_6839c97557ddf.jpg',
                'payment' => 'cash,kpr',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_listing' => 2,
                'judul' => 'Apartemen Modern Surabaya',
                'deskripsi' => 'Apartemen dengan view kota Surabaya dan fasilitas premium.',
                'tipe' => 'apartemen',
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'harga' => 750000000,
                'lokasi' => 'Jl. Basuki Rahmat, Surabaya',
                'lantai' => 15,
                'id_agent' => 'AG001',
                'luas_tanah' => 80,
                'luas_bangunan' => 100,
                'provinsi' => 'Jawa Timur',
                'kota' => 'Surabaya',
                'kelurahan' => 'Tegalsari',
                'sertifikat' => 'HGB',
                'orientation' => 'utara',
                'status' => 'Tersedia',
                'gambar' => '/storage/property-images/1748617589_6839c97557ddf.jpg',
                'payment' => 'cash',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_listing' => 3,
                'judul' => 'Ruko Strategis Bandung',
                'deskripsi' => 'Ruko 2 lantai dekat pusat perbelanjaan.',
                'tipe' => 'ruko',
                'kamar_tidur' => 1,
                'kamar_mandi' => 2,
                'harga' => 1250000000,
                'lokasi' => 'Jl. Riau No. 5, Bandung',
                'lantai' => 2,
                'id_agent' => 'AG001',
                'luas_tanah' => 150,
                'luas_bangunan' => 200,
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bandung',
                'kelurahan' => 'Cihapit',
                'sertifikat' => 'AJB',
                'orientation' => 'barat',
                'status' => 'Tersedia',
                'gambar' => '/storage/property-images/1748617589_6839c97557ddf.jpg',
                'payment' => 'cash,kpr',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_listing' => 4,
                'judul' => 'Rumah Mewah Di Lebak Arum',
                'deskripsi' => 'Rumahnya felicia',
                'tipe' => 'rumah',
                'kamar_tidur' => 1,
                'kamar_mandi' => 2,
                'harga' => 1250000000,
                'lokasi' => 'Jl. lebak arum permai utara 1 no 7b',
                'lantai' => 2,
                'id_agent' => 'AG001',
                'luas_tanah' => 150,
                'luas_bangunan' => 200,
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bandung',
                'kelurahan' => 'Cihapit',
                'sertifikat' => 'AJB',
                'orientation' => 'barat',
                'status' => 'Tersedia',
                'gambar' => '/storage/property-images/1748617589_6839c97557ddf.jpg',
                'payment' => 'cash,kpr',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);

        DB::table('informasi_klien')->insert([
            [
                'id_account'        => 'AC005',
                'berlaku_hingga'    => '2025-12-31',
                'gambar_ktp'        => '/storage/ktp/ktp_example.jpg',
                'alamat'            => 'Jl. Mawar No. 123, Jakarta Selatan',
                'nik'               => '317342424343423',
                'pekerjaan'         => 'Karyawan Swasta',
                'jenis_kelamin'     => 'Laki-laki',
                'status_verifikasi' => 'Terverifikasi',
                'nomor_rekening'    => '1234567890',
                'nama_bank'         => 'Bank BCA',
                'atas_nama'         => 'John Doe',
                'nomor_npwp'        => '09.888.999.0-123.000',
                'gambar_npwp'       => '/storage/npwp/npwp.jpg',
                'tanggal_dibuat'    => now(),
                'tanggal_diupdate'  => now(),
            ],
        ]);

        DB::table('property_interests')->insert([
            [
                'id_listing'       => 4,
                'id_klien'         => 'AC005',
                'status'           => 'FollowUp',
                'tanggal_dibuat'   => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);
    }
}
