<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('account')->insert([
            [
                'id_account' => 'AC001',
                'username' => 'jason',
                'email' => 'jasoncliendo@gmail.com',
                'nama' => 'Jason',
                'tanggal_lahir' => '2003-08-01',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '0881026757313',
                'roles' => 'Owner',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC002',
                'username' => 'lieming',
                'email' => 'solusindosinergilelang@gmail.com',
                'nama' => 'lieming',
                'tanggal_lahir' => '1992-07-21',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082233445566',
                'roles' => 'Pengosongan',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC003',
                'username' => 'agnesia',
                'email' => 'agnesia@gmail.com',
                'nama' => 'agnes',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '083344556677',
                'roles' => 'Register',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC004',
                'username' => 'felicia',
                'email' => 'ftiffany04a@gmail.com',
                'nama' => 'felicia',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082266100102',
                'roles' => 'Agent',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
            [
                'id_account' => 'AC005',
                'username' => 'nyonyo',
                'email' => 'bryan@gmail.com',
                'nama' => 'bryan',
                'tanggal_lahir' => '1990-12-05',
                'password' => '123123',
                'kota' => 'KOTA SURABAYA',
                'kecamatan' => 'Manukan',
                'nomor_telepon' => '082266100102',
                'roles' => 'User',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);

        // Tabel Agent
        DB::table('agent')->insert([
            [
                'id_agent' => 'AG001',
                'id_account' => 'AC004',
                'nama' => 'felicia',
                'nomor_telepon' => '082266100102',
                'email' => 'ftiffany04a@gmail.com',
                'instagram' => 'felicia_tiffany',
                'facebook' => 'fb.com/jevon',
                'jadwal' => '2025-06-01',
                'picture' => '/storage/agents/felicia.jpg',
                'kota' => 'Surabaya',
                'status' => 'Aktif',
                'rating' => 4,
                'jumlah_penjualan' => 2,
                'lokasi_kerja' => 'Surabaya Barat',
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'gambar_ktp' => '/storage/ktp/jevon_ktp.jpg',
                'gambar_npwp' => '/storage/npwp/jevon_npwp.jpg'
            ],

        ]);

        DB::table('property')->insert([
            [
                'id_listing' => 1,
                'judul' => 'Rumah Modern 2 Lantai di Bekasi',
                'deskripsi' => 'Rumah modern dengan desain minimalis di kawasan strategis Bekasi, cocok untuk keluarga muda.',
                'tipe' => 'rumah',
                'harga' => 1250000000,
                'lokasi' => 'Jl. Raya Pondok Ungu No. 15, Bekasi',
                'luas' => 200,
                'provinsi' => 'JAWA BARAT',
                'kota' => 'KOTA SURABAYA',
                'kelurahan' => 'Lakarsantri',
                'kecamatan' => 'Lakarsantri',
                'sertifikat' => 'SHM',
                'status' => 'Tersedia',
                'gambar' => 'https://file.lelang.go.id/lelang/photo_barang/2025/05/27/whatsapp-image-2025-05-27-at-15-51-36-1-6835708243d4b743993655.jpg',
                'payment' => 'cash,kpr',
                'uang_jaminan' => 100000000,
                'batas_akhir_jaminan' => now()->addDays(10),
                'batas_akhir_penawaran' => now()->addDays(12),
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'id_agent' => 'AG001',
            ],
            [
                'id_listing' => 2,
                'judul' => 'Tanah Strategis di Surabaya',
                'deskripsi' => 'Tanah kavling siap bangun dengan akses mudah ke jalan utama, cocok untuk investasi.',
                'tipe' => 'tanah',
                'harga' => 800000000,
                'lokasi' => 'Jl. Ahmad Yani, Surabaya',
                'luas' => 500,
                'provinsi' => 'JAWA TIMUR',
                'kota' => 'KOTA SURABAYA',
                'kelurahan' => 'Lakarsantri',
                'kecamatan' => 'Lakarsantri',
                'sertifikat' => 'HGB',
                'status' => 'Tersedia',
                'gambar' => 'https://file.lelang.go.id/lelang/photo_barang/2025/05/27/whatsapp-image-2025-05-27-at-15-51-36-1-6835708243d4b743993655.jpg',
                'payment' => 'cash',
                'uang_jaminan' => 60000000,
                'batas_akhir_jaminan' => now()->addDays(5),
                'batas_akhir_penawaran' => now()->addDays(7),
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'id_agent' => 'AG001',
            ],
            [
                'id_listing' => 3,
                'judul' => 'Apartemen Premium di Jakarta Selatan',
                'deskripsi' => 'Apartemen fully furnished dengan fasilitas gym & swimming pool, dekat dengan mall besar.',
                'tipe' => 'apartemen',
                'harga' => 1750000000,
                'lokasi' => 'Jl. TB Simatupang, Jakarta Selatan',
                'luas' => 90,
                'provinsi' => 'DKI JAKARTA',
                'kota' => 'KOTA SURABAYA',
                'kelurahan' => 'Lakarsantri',
                'kecamatan' => 'Lakarsantri',
                'sertifikat' => 'Strata Title',
                'status' => 'Tersedia',
                'gambar' => 'https://file.lelang.go.id/lelang/photo_barang/2025/05/27/whatsapp-image-2025-05-27-at-15-51-36-1-6835708243d4b743993655.jpg',
                'payment' => 'cash,kpr',
                'uang_jaminan' => 200000000,
                'batas_akhir_jaminan' => now()->addDays(15),
                'batas_akhir_penawaran' => now()->addDays(18),
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'id_agent' => 'AG001',
            ],
            [
                'id_listing' => 4,
                'judul' => 'Gudang Luas di Semarang',
                'deskripsi' => 'Gudang dengan akses kontainer, lokasi strategis dekat pelabuhan Tanjung Emas.',
                'tipe' => 'gudang',
                'harga' => 3250000000,
                'lokasi' => 'Jl. Kaligawe, Semarang',
                'luas' => 1500,
                'provinsi' => 'JAWA TENGAH',
                'kota' => 'KOTA SURABAYA',
                'kelurahan' => 'Lakarsantri',
                'kecamatan' => 'Lakarsantri',
                'sertifikat' => 'SHM',
                'status' => 'Tersedia',
                'gambar' => 'https://file.lelang.go.id/lelang/photo_barang/2025/05/27/whatsapp-image-2025-05-27-at-15-51-36-1-6835708243d4b743993655.jpg',
                'payment' => 'cash',
                'uang_jaminan' => 500000000,
                'batas_akhir_jaminan' => now()->addDays(20),
                'batas_akhir_penawaran' => now()->addDays(22),
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'id_agent' => 'AG001',
            ],
            [
                'id_listing' => 5,
                'judul' => 'Pabrik Siap Pakai di Karawang',
                'deskripsi' => 'Pabrik luas dengan daya listrik besar, cocok untuk industri manufaktur.',
                'tipe' => 'pabrik',
                'harga' => 7500000000,
                'lokasi' => 'Kawasan Industri KIIC, Karawang',
                'luas' => 2500,
                'provinsi' => 'JAWA BARAT',
                'kota' => 'KOTA SURABAYA',
                'kelurahan' => 'Lakarsantri',
                'kecamatan' => 'Lakarsantri',
                'sertifikat' => 'HGB',
                'status' => 'Tersedia',
                'gambar' => 'https://file.lelang.go.id/lelang/photo_barang/2025/05/27/whatsapp-image-2025-05-27-at-15-51-36-1-6835708243d4b743993655.jpg',
                'payment' => 'cash',
                'uang_jaminan' => 1000000000,
                'batas_akhir_jaminan' => now()->addDays(25),
                'batas_akhir_penawaran' => now()->addDays(28),
                'tanggal_dibuat' => now(),
                'tanggal_diupdate' => now(),
                'id_agent' => 'AG001',
            ],
        ]);

        DB::table('informasi_klien')->insert([
            [
                'id_account'        => 'AC005',
                'berlaku_hingga'    => '2025-12-31',
                'gambar_ktp'        => '/storage/ktp/ktp_example.jpg',
                'alamat'            => 'Jl. Mawar No. 123, Jakarta Selatan',
                'nik'               => '317342424343423',
                'pekerjaan'         => 'Karyawan Swasta',
                'jenis_kelamin'     => 'Laki-laki',
                'status_verifikasi' => 'Terverifikasi',
                'nomor_rekening'    => '1234567890',
                'nama_bank'         => 'Bank BCA',
                'atas_nama'         => 'John Doe',
                'nomor_npwp'        => '09.888.999.0-123.000',
                'gambar_npwp'       => '/storage/npwp/npwp.jpg',
                'tanggal_dibuat'    => now(),
                'tanggal_diupdate'  => now(),
            ],
        ]);

        DB::table('property_interests')->insert([
            [
                'id_listing'       => 4,
                'id_klien'         => 'AC005',
                'status'           => 'FollowUp',
                'tanggal_dibuat'   => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);

        DB::table('transaction')->insert([
            [
                'id_listing'       => 4,
                'id_klien'         => 'AC005',
                'status'           => 'FollowUp',
                'tanggal_dibuat'   => now(),
                'tanggal_diupdate' => now(),
            ],
        ]);
    }
}
