
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  firebird:
    image: jacobalberty/firebird:latest
    restart: always
    ports:
      - "3050:3050"
    environment:
      ISC_PASSWORD: masterkey
    volumes:
      - ./storage:/firebird/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

